Repository astarte-platform/astarte_rpc, pull requests merged in 2020-05, with the labels that each got.

#26 Support ssl for RabbitMQ connections
  lib/astarte_rpc/config.ex
  mix.exs
  mix.lock
  test/astarte/rpc/amqp_options_test.exs
Labels: enhancement

#27 Prepare 0.11.1 release
  CHANGELOG.md
  mix.exs
Labels: chore

#28 Default max certificate chain length to 10
  CHANGELOG.md
  lib/astarte_rpc/config.ex
Labels: user experience
